type: group
fields:
  author:
    label: 
      nl: Auteur
      en: Author
      fr: Auteur
    type: users
    multiple: false
    required: true
  published:
    label: 
      nl: Publicatiedatum
      en: Publication date
      fr: Date de publication
    type: date
    default: today
    required: true
