title: Site

tabs:
# tab
  pages:
    label:
      en: Pages
      nl: Pagina's
    icon: page
    columns:
    # column
      listed:
        width: 1/3
        sections:
          listed:
            label:
              en: Main pages
              nl: Hoofdpagina's
            type: pages
            status: listed
    # column
      unlisted:
        width: 1/3
        sections:
          unlisted:
            label:
              en: Extra pages
              nl: Extra pagina's
            type: pages
            status: unlisted
    # column
      drafts:
        width: 1/3
        sections:
          drafts:
            label:
              en: Drafts
              nl: Concepten
            type: pages
            status: draft
            create:
              - default
# tab
  settings:
    label:
      en: Settings
      nl: Instellingen
    icon: cog
    columns:
    # column
      settings:
        width: 2/3
        sections:
          settings:
            type: fields
            fields:
